import { PayloadAction, createSlice } from "@reduxjs/toolkit";
import { List } from "postcss/lib/list";
import { Key } from "react";
import { ListFormat } from "typescript";

export type laptopType = {
  id: number;
  type: string;
  subject: string;
  image: string;
  name: string;
  price: number;
  color: string;
  creator: string;
  cpu: string;
  ram: number;
  ramType: string;
  storage: string;
  graphic: string;
  graphicStorage: number;
  screen?: number;
  resolation?: string;
  warranty: number;
  motherBoard?: string;
};

const initialState: laptopType[] = [
  {
    id: 1,
    type: "laptop",
    subject: "لنوو",
    image: "ip3-1",
    name: "IdeaPad3",
    price: 13615420,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-10110U",
    ram: 4,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphic",
    graphicStorage: 1,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 2,
    type: "laptop",
    subject: "لنوو",
    image: "ip3-2",
    name: "IdeaPad3",
    price: 14088820,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-1115G4",
    ram: 4,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphic",
    graphicStorage: 1,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 3,
    type: "laptop",
    subject: "لنوو",
    image: "ip3-3",
    name: "IdeaPad3",
    price: 15788820,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-10110U",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphic",
    graphicStorage: 1,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 4,
    type: "laptop",
    subject: "لنوو",
    image: "ip3-4",
    name: "IdeaPad3",
    price: 19888820,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-9400f",
    ram: 16,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphic",
    graphicStorage: 2,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 5,
    type: "pc",
    subject: "اداری",
    image: "pc-1",
    name: "E13 کامپیوتر اداری",
    price: 14200000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-10100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphic",
    graphicStorage: 2,
    motherBoard: "H510M",
    warranty: 18,
  },
  {
    id: 6,
    type: "pc",
    subject: "اداری",
    image: "pc-2",
    name: "E14 کامپیوتر اداری",
    price: 15800000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "2TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 7,
    type: "pc",
    subject: "رندرینگ",
    image: "pc-3",
    name: "R23 کامیپوتر رندرینگ",
    price: 43800000,
    color: "سیاه",
    creator: "intel",
    cpu: "i7-12700K",
    ram: 32,
    ramType: "DDR4",
    storage: "2TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 4,
    motherBoard: "Z690-P D4",
    warranty: 18,
  },
  {
    id: 8,
    type: "pc",
    subject: "رندرینگ",
    image: "pc-4",
    name: "R17 کامیپوتر رندرینگ",
    price: 50802000,
    color: "سیاه",
    creator: "intel",
    cpu: "i5-12600K",
    ram: 32,
    ramType: "DDR4",
    storage: "4TB-HDD",
    graphic: "ZOTAC GTX 1650",
    graphicStorage: 4,
    motherBoard: "Z690-UD",
    warranty: 18,
  },
  {
    id: 9,
    type: "pc",
    subject: "گیمینگ",
    image: "pc-5",
    name: "G24 کامیپوتر گیمینگ",
    price: 20802000,
    color: "سیاه",
    creator: "intel",
    cpu: "i5-12400",
    ram: 32,
    ramType: "DDR4",
    storage: "4TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 10,
    type: "pc",
    subject: "حسابداری",
    image: "pc-6",
    name: "A14 کامیپوتر حسابداری",
    price: 18850000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 11,
    type: "pc",
    subject: "طراحی",
    image: "pc-7",
    name: "D23 کامیپوتر طراحی",
    price: 54750000,
    color: "سیاه",
    creator: "intel",
    cpu: "i7-12700K",
    ram: 16,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "Z690-P D4",
    warranty: 18,
  },
  {
    id: 12,
    type: "pc",
    subject: "خانگی",
    image: "pc-8",
    name: "H16 کامیپوتر خانگی",
    price: 23050000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 13,
    type: "pc",
    subject: "دانش آموزی",
    image: "pc-9",
    name: "S14 کامیپوتر دانش آموزی",
    price: 18950000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 2,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 14,
    type: "pc",
    subject: "دانش جویی",
    image: "pc-10",
    name: "S14 کامیپوتر دانش جویی",
    price: 26000000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 4,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 15,
    type: "pc",
    subject: "تریدینگ",
    image: "pc-11",
    name: "T17 کامیپوتر تریدینگ",
    price: 24850000,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 4,
    motherBoard: "H610M-K",
    warranty: 18,
  },
  {
    id: 16,
    type: "laptop",
    subject: "ایسوس",
    image: "laptop-asus1",
    name: "لپ تاپ ایسوس",
    price: 17988820,
    color: "سیاه",
    creator: "intel",
    cpu: "i3-12100",
    ram: 8,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "intel UHD Graphics 730",
    graphicStorage: 4,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 17,
    type: "laptop",
    subject: "ایسوس",
    image: "laptop-tuf",
    name: "لپ تاپ ایسوس تاف گیمینگ",
    price: 38788820,
    color: "سیاه",
    creator: "invidia",
    cpu: "i5-11400H",
    ram: 16,
    ramType: "DDR4",
    storage: "1TB-HDD",
    graphic: "RTX 3050",
    graphicStorage: 4,
    screen: 15.6,
    resolation: "1920 * 1080",
    warranty: 18,
  },
  {
    id: 18,
    type: "access",
    subject: "رم",
    image: "ram",
    name: "رم کامپیوتر 16 گیگ",
    price: 3600000,
    color: "سیاه",
    creator: "G-Skill",
    cpu: "i5-11400H",
    ram: 16,
    ramType: "DDR4",
    storage: "16GB",
    graphic: "0",
    graphicStorage: 16,
    warranty: 18,
  },
  {
    id: 19,
    type: "access",
    subject: "خنک کننده",
    image: "cooler",
    name: "خنک کننده پردازنده دیپ کول",
    price: 1848181,
    color: "سیاه",
    creator: "G-Skill",
    cpu: "i5-11400H",
    ram: 16,
    ramType: "DDR4",
    storage: "16GB",
    graphic: "0",
    graphicStorage: 16,
    warranty: 18,
  },
  {
    id: 20,
    type: "access",
    subject: "مادربرد",
    image: "motherboard",
    name: "مادربرد گیگابایت",
    price: 4000000,
    color: "سیاه",
    creator: "G-Skill",
    cpu: "i5-11400H",
    ram: 16,
    ramType: "DDR4",
    storage: "16GB",
    graphic: "LGA 1200",
    graphicStorage: 4,
    motherBoard: "H510M S2H",
    warranty: 18,
  },
  {
    id: 21,
    type: "access",
    subject: "گرافیک",
    image: "graphic",
    name: "کارت گرافیک 3060",
    price: 19500000,
    color: "سیاه",
    creator: "G-Skill",
    cpu: "i5-11400H",
    ram: 16,
    ramType: "DDR4",
    storage: "16GB",
    graphic: "LGA 1200",
    graphicStorage: 4,
    motherBoard: "H510M S2H",
    warranty: 18,
  },
  {
    id: 22,
    type: "access",
    subject: "پردازنده",
    image: "cpu",
    name: " i3 10100F پردازنده",
    price: 3350000,
    color: "سیاه",
    creator: "G-Skill",
    cpu: "i3-10100F",
    ram: 16,
    ramType: "DDR4",
    storage: "16GB",
    graphic: "LGA 1200",
    graphicStorage: 4,
    motherBoard: "H510M S2H",
    warranty: 18,
  },
];

const laptopSlice = createSlice({
  name: "laptopSlice",
  initialState,
  reducers: {},
});

export default laptopSlice.reducer;
